# Generated by Django 5.2.8 on 2026-09-24

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models
from django.db.models import Count


EMBEDDING_DIMENSION = 768


def select_embedding_to_keep(embeddings):
    """Prefer the newest valid vector, or the newest retryable row."""
    for embedding in embeddings:
        vector = embedding.embedding
        if vector is not None and len(vector) == EMBEDDING_DIMENSION:
            return embedding
    return embeddings[0]


def prepare_existing_embeddings(apps, schema_editor):
    """Retain one usable embedding row per document before adding uniqueness."""
    ProductEmbedding = apps.get_model("ai_search", "ProductEmbedding")

    duplicate_document_ids = list(
        ProductEmbedding.objects.values("product_document_id")
        .annotate(embedding_count=Count("pk"))
        .filter(embedding_count__gt=1)
        .values_list("product_document_id", flat=True)
    )

    for document_id in duplicate_document_ids:
        candidates = list(
            ProductEmbedding.objects.filter(product_document_id=document_id)
            .order_by("-created_at", "-pk")
        )
        embedding = select_embedding_to_keep(candidates)
        ProductEmbedding.objects.filter(
            product_document_id=document_id,
        ).exclude(pk=embedding.pk).delete()

    table_name = schema_editor.quote_name(ProductEmbedding._meta.db_table)
    schema_editor.execute(
        f"UPDATE {table_name} SET embedding = NULL "
        f"WHERE embedding IS NOT NULL "
        f"AND vector_dims(embedding) <> {EMBEDDING_DIMENSION}"
    )


class Migration(migrations.Migration):

    dependencies = [
        ("ai_search", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="productembedding",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.RunPython(
            prepare_existing_embeddings,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="productembedding",
            name="embedding",
            field=pgvector.django.vector.VectorField(
                blank=True,
                dimensions=768,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="productembedding",
            name="product_document",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="embedding",
                to="ai_search.productsearchdocument",
            ),
        ),
    ]
