# Generated by Django 5.2.8 on 2026-09-24 05:56

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import pgvector.django.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_search', '0002_harden_product_embeddings'),
        ('products', '0010_order_checkout_token_order_exchange_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productembedding',
            name='attempt_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productembedding',
            name='content_hash',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='productembedding',
            name='error_message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='productembedding',
            name='last_attempt_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productembedding',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('READY', 'Ready'), ('FAILED', 'Failed')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='productsearchdocument',
            name='content_hash',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='productsearchdocument',
            name='embedding_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddIndex(
            model_name='productembedding',
            index=pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='embedding_hnsw_cosine', opclasses=['vector_cosine_ops']),
        ),
        migrations.AddIndex(
            model_name='productsearchdocument',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.search.SearchVector('searchable_text', config='simple'), name='search_doc_fts_gin'),
        ),
    ]
