# Generated by Django 5.2.8 on 2026-09-24 07:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_search', '0003_sprint2_embedding_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchQueryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_query', models.CharField(help_text='The raw query string entered by the user.', max_length=500)),
                ('extracted_filters', models.JSONField(blank=True, default=dict, help_text='Structured intent and filters extracted from the query.')),
                ('result_count', models.IntegerField(default=0, help_text='Number of results returned.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, help_text='User who performed the search, if authenticated.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Search Query Log',
                'verbose_name_plural': 'Search Query Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
