# Generated by Django 5.2.8 on 2026-09-24 08:50

from django.db import migrations, models


def populate_normalized_queries(apps, schema_editor):
    SearchQueryLog = apps.get_model('ai_search', 'SearchQueryLog')
    rows = SearchQueryLog.objects.only('pk', 'query').iterator(chunk_size=500)
    for row in rows:
        row.normalized_query = ' '.join(row.query.split()).casefold()
        row.save(update_fields=['normalized_query'])


class Migration(migrations.Migration):

    dependencies = [
        ('ai_search', '0004_sprint3_query_log'),
    ]

    operations = [
        migrations.RenameField(
            model_name='searchquerylog',
            old_name='extracted_filters',
            new_name='analysis',
        ),
        migrations.RenameField(
            model_name='searchquerylog',
            old_name='original_query',
            new_name='query',
        ),
        migrations.RemoveField(
            model_name='searchquerylog',
            name='user',
        ),
        migrations.AddField(
            model_name='searchquerylog',
            name='cache_hit',
            field=models.BooleanField(default=False, help_text='Whether structured query analysis came from cache.'),
        ),
        migrations.AddField(
            model_name='searchquerylog',
            name='execution_time_ms',
            field=models.FloatField(default=0.0, help_text='End-to-end search execution time in milliseconds.'),
        ),
        migrations.AddField(
            model_name='searchquerylog',
            name='normalized_query',
            field=models.CharField(db_index=True, default='', help_text='Canonical query used for analytics and cache identity.', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='searchquerylog',
            name='timings',
            field=models.JSONField(blank=True, default=dict, help_text='Per-phase retrieval timings in milliseconds.'),
        ),
        migrations.AlterField(
            model_name='searchquerylog',
            name='result_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of results returned.'),
        ),
        migrations.AlterField(
            model_name='searchquerylog',
            name='query',
            field=models.CharField(help_text='The validated search query.', max_length=500),
        ),
        migrations.RunPython(
            populate_normalized_queries,
            migrations.RunPython.noop,
        ),
    ]
