# Generated by Django 5.2.8 on 2026-09-24 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.TextField()),
                ('intent', models.CharField(blank=True, max_length=100, null=True)),
                ('retrieval_time_ms', models.FloatField(blank=True, null=True)),
                ('context_time_ms', models.FloatField(blank=True, null=True)),
                ('llm_time_ms', models.FloatField(blank=True, null=True)),
                ('total_time_ms', models.FloatField(blank=True, null=True)),
                ('token_usage', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_logs', to='ai_assistant.conversation')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
