# Generated by Django 5.2.8 on 2026-09-24 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_order_checkout_token_order_exchange_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='embedding_description',
            field=models.TextField(blank=True, help_text='Detailed semantic description used exclusively for AI search and embeddings. Not displayed to customers on the frontend.', null=True),
        ),
    ]
